### ISSUE TITLE
Country View UI Issue

### ISSUE THREAD

**Issue by BigBoss618** [Coyote-31/eu4_mod_Royal_Eagle_UI#2]
UI seems to leave an empty row at the top of the Country View as seen here https://prnt.sc/xgumst when selecting the Estates Tab

**Comment by Coyote-31** [comment]
I think you have a mod changing `.gui` files. In this case it is `countryestatesview.gui`.
I can't see all the displayed view in your screen but it's look like nothing is displayed like in my mod as you can see here :

![Country Estates View](https://steamuserimages-a.akamaihd.net/ugc/1645469340559254901/6836044B3A813FFDBA429B6F5C4798B808B05FC1/)

Is this happen in other view of the country menus (like economy or military for exemple) ?
And is this happen when only RoyalEagleUI mod is activated ?

**Comment by BigBoss618** [comment]
Yeah that’s the only tab it happens on. Will try without IGE etc (Which edit the UI)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Coyote-31** [comment]
To try to fix this : 
- Is this happen when only RoyalEagleUI mod is activated ?
- Can you screenshot your whole screen to see if all the menu is broken ?

**Comment by Coyote-31** [comment]
Can't find this bug I assume it's not from this mod

**Comment by BigBoss618** [comment]
It’s probably GE which edits the UI as well but I have been suuuuuper busy these days with FU and I had no time to check it out I sincerely apologize!


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
